# Welcome to Jupyter!

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook

In [1]:
#Question 1:

import numpy as np
print(np.arange(2, 50, 3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
#Question 2:

import numpy as np
lst1 = []
lst2 = []
for i in range(0,5):
    ele1 = input()
    lst1.append(ele1)
for i in range(0,5):
    ele2 = input()
    lst2.append(ele2)
arr1 = np.array(lst1)
arr2 = np.array(lst2)
arr = np.concatenate((arr1, arr2))
print(arr)
print(np.sort(arr))

apple
banana
orange
pear
peach
pineapple
kiwi
guava
papaya
cucumber
['apple' 'banana' 'orange' 'pear' 'peach' 'pineapple' 'kiwi' 'guava'
 'papaya' 'cucumber']
['apple' 'banana' 'cucumber' 'guava' 'kiwi' 'orange' 'papaya' 'peach'
 'pear' 'pineapple']


In [3]:
#Question 3:

import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr.ndim)    #output: 3
print(arr.size)   #output: 24 

3
24


In [4]:
#Question 4:

import numpy as np
arr1 = np.arange(0, 10)
print(arr1)
arr2 = np.reshape(arr1, (2,5))
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
#Question 5:

import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a, b))
print(np.vstack(c))
print(np.hstack(c))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[1 2 3 4 5 6 7 8]


In [6]:
#Question 6:

input_list = [1,2,3,4,4,3,7,5,1,8,4,1,2]
lst = []
count = 0
for item in input_list:
    if item not in lst:
        lst.append(item)
        count += 1
print("Unique items in list are: {}".format(lst))
print("Counts of unique items are: {}".format(count))

Unique items in list are: [1, 2, 3, 4, 7, 5, 8]
Counts of unique items are: 7
